sindy/feature_library/custom_library.py
sindy/feature_library/fourier_library.py
sindy/feature_library/polynomial_library.py
sindy/optimizers/base.py
sindy/utils/base.py

Changed `BaseOptimizer` class so that it inherits from `sklearn.linear_model.LinearRegression` instead of `sklearn.linear_model.base.LinearModel`. sklearn was throwing a warning that we won't be able to import from `sklearn.linear_model.base` in the future, i.e.
```/home2/bdesilva/.local/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144
/home2/bdesilva/.local/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.linear_model.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
warnings.warn(message, FutureWarning)
```
I also
- Added …

Remove dependence on sklearn.linear_model.base.

---

.git_archival.txt
pysindy/__init__.py
requirements-dev.txt
setup.py

```
$ python -c "import pysindy; print(pysindy.__version__)"
0.10.1.dev127+gf84af35.d20200116
```
Is derived from the latest tag (`v0.10.0`) . You can read more about this here: https://github.com/pypa/setuptools_scm/

Use setuptools_scm for tag based versioning

---

pysindy/pysindy.py

Features names were getting converted from ['x0','x1','x2'] to ['1', 'x0', 'x1', 'x2', 'x0^2', ...] twice, once in SINDy.equations() and once in utils.equation(). This was leading to incorrect printing of the equations. I removed the conversion happening in the SINDy.equations() method, so this conversion only happens in utils.equation().

changed sindy equations method to correctly print equations

---

.github/workflows/main.yml

The previous setup caused the following error during the "Upload coverage to Codecov" action.
`No coverage report found.`
I've modified the configuration to more closely resemble [this example](https://github.com/codecov/codecov-action).

Specify xml coverage file for codecov.

---

pysindy/optimizers/base.py
pysindy/optimizers/elastic_net.py
pysindy/optimizers/lasso.py
pysindy/optimizers/sr3.py
pysindy/optimizers/stlsq.py
test/optimizers/test_optimizers.py

Explicitly pass all parameters through optimizer `__init__` functions to base class `BaseOptimizer` `__init__` function. This fixes #37 . Move the `max_iter` parameter to `BaseOptimizer`.
I also updated the unit test for `unbias` to avoid division by zero.

Fix handling of parameters in optimizer init functions.

---

pysindy/pysindy.py
test/test_pysindy.py

Added a `quiet` option to suppress optimizer warnings when calling `SINDy.fit()`

Quiet mode

---

pysindy/optimizers/stlsq.py

Change default value of `alpha` from 0 to 0.1. Some library choices result in ill-conditioned linear systems that require regularization to invert. Since we set `unbias=True` by default, we should also perform regularization by default.

Set nonzero default regularization for STLSQ.

---

pysindy/optimizers/sindy_optimizer.py
test/optimizers/test_optimizers.py

Addresses #50 by having `SINDyOptimizer` perform checks for the various attributes and methods used in the optimizer that's passed in.
An `AttributeError` is now raised if the `fit` and `predict` methods and the `coef_` attribute are missing. If there is no `intercept_` attribute, the intercept is just set to `0.0`. If there are no `fit_intercept` and `normalize` attributes, these are just set to `False` for the unbiasing. If anyone has alternative suggestions for how these should be handled, feel free to discuss.

Check optimizer attributes

---

pysindy/optimizers/sr3.py
pysindy/optimizers/stlsq.py
requirements-dev.txt
test/property_tests/test_optimizers_complexity.py

This add the suggested by @sixpearls in review https://github.com/openjournals/joss-reviews/issues/2104
The test uses hypothesis and sklearns make_dataset to construct a random regression dataset and verifies that less regularized optimizers are more complex.

Add property test for optimizers complexity

---

docs/conf.py
docs/index.rst
example/feature_overview.ipynb
requirements-dev.txt

Related to #46 .
Include `example/feature_overview.ipynb` in Sphinx documentation via nbsphinx.
I've also added a binder link for `feature_overview.ipynb` so that users can play around with the notebook without downloading the package and all its dependencies.

Add feature_overview.ipynb to documentation. Include binder link.

---

examples/2_original_paper.ipynb

There was a problem with how a math equation was formatted in original paper notebook. The equation was properly displayed in my local notebook, but not on Github nor in the sphinx documentation.
I would have just pushed directly to master, but I wanted to make sure Github rendered the equation properly.

Fix math formatting.

---

pysindy/optimizers/stlsq.py
pysindy/pysindy.py

This is to fix the issues raised in [Issue #68](https://github.com/dynamicslab/pysindy/issues/68) 
Also, I made some suggested changes to formatting of warning messages and a doc string.

Change to SINDy init defaults for optimizer, feature_library, and differentiation_method

---

test/property_tests/test_optimizers_complexity.py

Updates optimizer complexity test to compare average complexity across 5 datasets to account for noise and non-normalized optimizer parameters. See #74.

Average over 5 datasets when checking complexity

---

pysindy/feature_library/custom_library.py
pysindy/optimizers/base.py
requirements.txt
test/optimizers/test_optimizers.py

* Updates required version of Scikit-learn from 0.21 to 0.23. The `check_is_fit` function had an extra positional argument `attributes` that version 0.23 makes into a keyword argument. Our calls to `check_is_fit` don't use the positional argument. See #81.
* Moves instantiation of some `BaseOptimizer` internal attributes (`coef_`, `history_`, and `ind_`) to the `fit` function. Previously these were defined in the class `__init__` function, causing the optimizers to appear as if they were fit before they actually were.
* Adds more stringent unit tests for checking when optimizers have been fit
* Adds a fit check to the `ComplexityMixin` class

Fix check fitted

---

examples/1_feature_overview.ipynb
examples/4_scikit_learn_compatibility.ipynb
pysindy/differentiation/base.py
pysindy/pysindy.py
pysindy/utils/base.py
test/test_pysindy.py
test/test_sindyc.py

The main contribution of this pull request is to enable Scikit-learn compatible cross-validation #7. The major changes are as follows:
* Add `t_default` parameter to the `SINDy` class. The default time step is still 1, but the user can also set the default to be something different using this parameter. Added unit tests for `t_default`
* Made `process_multiple_trajectories` into an internal function by prepending an underscore to its name
* Differentiation objects now inherit from sklearn's `BaseEstimator` (necessary for cross-validation)
* Added examples of cross-validation and using `t_default`
Bug fixes
* We were using sklearn's `PolynomialFeatures` instead of our own `PolynomialLibrary` as the default argument for `feature_library`
* Added a check to `validate_input` for t being a …

Cross-validation

---

pysindy/optimizers/sr3.py
test/conftest.py
test/optimizers/test_optimizers.py

This pull request adds the option to trim corrupt data when using SR3. The user specifies what fraction of the input samples should be trimmed, and the optimizer will simultaneously select which samples to remove and fit the coefficient matrix using the untrimmed samples. This is done using an iterative optimization approach. More details can be found [here](https://arxiv.org/abs/1906.10612).
I have not yet updated the examples to include an example of sparse data trimming, and I'll update the pull request when this is included. 
Additional note: In the current implementation, the user will need to explicitly use unbias=False to use trimming effectively. This option is set in SINDyOptimizer, rather than in the optimizer itself. If anyone has a suggestion for how to make this false by …

Add optional corrupt data trimming to SR3

---

pysindy/optimizers/constrained_sr3.py
pysindy/pysindy.py
test/conftest.py
test/test_sindyc.py

Fixes the bug raised in #107, where `SINDy.predict` failed for discrete systems with multiple control variables. The problem was caused by the `SINDy.predict` method being fed a 1D vector of control inputs, which was then interpreted as a column vector. The fix was simply to force the vector to be interpreted as a row vector with `np.newaxis`.

[Bug fix] Multivariable control inputs for discrete systems

---

pysindy/feature_library/weak_pde_library.py

I found an incorrectly named variable in thew weak pde library. It made weak form example notebooks fail. I have fixed it and checked that the weakform notebook can now run.

bugfix - added missing _ to n_input_features_

---

pysindy/optimizers/frols.py
test/optimizers/test_optimizers.py

Test added: test_frols_error_linear_dependence().
Test fails on master, passes on this branch.  Fixes #191

ENH: Raise explicit error when FROLS has linearly dependent columns.

---

pysindy/differentiation/sindy_derivative.py
test/differentiation/test_differentiation_methods.py

Discovered a bug in how `SINDyDerivative` made a mistake with `set_params()`.  Previously, CV test was passing, but silently not updating parameters the way it should have.  See commit msg

BUG: SINDyDerivative set_params() missed sklearn interface

---

README.rst

In preparation for detaching fork from ohjeah/sparsereg.
Brian's email:
> I heard back from Markus today and he's fine with us detaching pysindy from sparsereg. But I told him we'd add a note and link at the top of the contributors section of the README to credit the initial contribution. What do you think?

DOC: Credit Markus in contributors

---

README.rst
test/conftest.py
test/test_notebooks.py

Allows testing of 3rd party examples that follow our format using new `test_external`.  Can verify this test works by pointing it to one of our own notebooks:
```
pytest -k test_external --external-notebook=examples/2_introduction_to_sindy
```

External examples

---

.pre-commit-config.yaml
pysindy/optimizers/miosr.py

Solves the CI error:
```
sphinx.errors.SphinxWarning: /home/runner/work/pysindy/pysindy/pysindy/optimizers/miosr.py:docstring of pysindy.optimizers.miosr.MIOSR:12:'any' reference target not found: model
```

DOC: Fix rst backticks to make CI green

---

pysindy/optimizers/trapping_sr3.py

Correct the indexing of projection tensor PL_unsym. Detail can be found in issue #258.

Update PL_unsym tensor in trapping_sr3.py

---

requirements-dev.txt

Codecov burninated their python package.  The codecov action should still work (I'll figure it out if it doesn't).  But it can't be a dependency or it will break the build.
https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259

Remove codecov package

---

.github/workflows/main.yml

Fixes #336 and limits duplicate CI runs (instead of every push and every pull, only run on pushes and pulls to master).

Troubleshooting Coverage Report

---

docs/conf.py

Sphinx reads the public methods of all classes, and if one inherits from sklearn, it reads that method's docstring.  If that method contains a relative link in the rst, sphinx needs to know where to link it.
This will fix the current CI failure, new as of scikit-learn 1.3.  I'm going to give this a suspense time of a day in case anyone wants to read it, but its a hotfix blocking any PR's CI so I want to move it fast.

Hotfix to enable intersphinx mapping to sklearn

---

examples/1_feature_overview/example.ipynb
examples/1_feature_overview/example.py
pysindy/pysindy.py
pysindy/utils/base.py
test/conftest.py
test/test_feature_library.py
test/test_pysindy.py
test/test_sindyc.py
test/utils/test_utils.py

For your consideration, here's a PR that implements #353.
tl;dr: IMO the `multiple_trajectories` argument is unneccessary and its removal simplifies calling signatures.  `SINDy.fit()` knows users want multiple trajectories when they pass a list of arrays - the same way many numpy functions have implicit behavior when passed a list of arrays instead of a single array.  OTOH, there exists a niche case where someone calls `fit()` with `x` as a list instead of an array and `t` as a float.  Previously, this would give an error, while in this PR, it would be allowed, similar to how submitting transposed data is allowed but doesn't give people what they think.  If people desire, I can add guard code around specifically this case, but my feeling is that the docstring is clear and the edge case …

Implicit multiple trajectories

---

pysindy/optimizers/base.py
pysindy/optimizers/constrained_sr3.py
pysindy/optimizers/frols.py
pysindy/optimizers/miosr.py
pysindy/optimizers/sindy_pi.py
pysindy/optimizers/sr3.py
pysindy/optimizers/ssr.py
pysindy/optimizers/stable_linear_sr3.py
pysindy/optimizers/stlsq.py
pysindy/optimizers/trapping_sr3.py
pysindy/optimizers/wrapped_optimizer.py
test/test_optimizers.py
test/test_optimizers_complexity.py

Fixes #338
Initialize fit_intercept in super() as False
Prevent the _tragic_ :sob: case of fitting both an intercept and a constant term, which could only otherwise be achieved with higher coupling and more tests.
Users can specify a constant term in the feature libraries using include_bias, where it exists, or by adding a constant term to a custom library and concatenating.
This change incurs a minor performance hit that disappears with scale, based upon how sklearn.LinearRegression fit the coefficient separately from the regression matrices.

CLN: Remove fit_intercept in optimizers

---

pysindy/optimizers/stable_linear_sr3.py
pysindy/optimizers/trapping_sr3.py
test/conftest.py
test/test_feature_library.py
test/test_optimizers.py
test/test_pysindy.py

Took the :microscope: to the slowest tests of `StableLinearSR3` and `TrappingSR3`.  Since test parameterization affected only the creation of CVXPY functions, I refactored that part out to speed up tests.
This drops test time from around 45 sec to ~30~ 14 sec
Closes #320
@akaptano, if you get a chance to review, that would be great, since this mostly affects your code.
Edit: @znicolaou, I made all the changes to Weak/PDE library tests here too.

Even faster tests :smoking: 

---

.readthedocs.yml

Current docs [fail to build](https://readthedocs.org/projects/pysindy/builds/21702823/) on RTFD because I added type annotations to Trapping.  We normally allow skipping the import of Trapping if `cvxpy` isn't installed, but RTFD needs to import it to understand the docstrings.

DOC: Add requirements for type annotations to readthedocs

---

pyproject.toml

Unfortunately, Gurobi dropped support for 9.5.2, and because it depends upon a license file, gurobipy 9.5.2 is officially broken without a manually added license.  Previously, we had been prevented from upgrading to 10.x because of a bug noted in #266.  I've recreated that bug with gurobipy 10.0.0, but tests pass in 10.0.1 to 10.0.3.  I've also requested gurobi release a 9.5.3 with an updated limited-size license.
This PR will also fix #303
<details>
<summary> Support email to gurobi </summary>
> As noted [here](https://support.gurobi.com/hc/en-us/articles/19487474933521-How-do-I-resolve-the-error-License-expired-2023-10-25-), the size-limited license with gurobipy 9.5.2 distributed via pip expired this year, disabling that release.
> 
> Our lab maintains an open-source modeling package …

Bump gurobipy verison

---

pysindy/utils/axes.py
test/utils/test_axes.py

`AxesArray.concatenate()` failed whenever the `out` argument was set. (See [docs](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)).
This PR enables the full calling signature of concatenate with AxesArrays.  It was discovered in some trapping work, as `np.stack` calls `concatenate` internally.
See the one added test, which fails on master branch and passes here.

BUG(axes): Make concat out param work

---

pysindy/optimizers/miosr.py
test/test_optimizers.py

Provides a reference implementation of option 3 in #456 .  At the time, I didn't know about `__setstate__` and `__getstate__`, but these are simpler and more straightforwards than `__reduce__`.
Test fails on master, passes on this branch.
Most of this change is from the example [here.](https://docs.python.org/3/library/pickle.html#handling-stateful-objects)

feat(optimizers): Enable pickling of MIOSR optimizer

---

.github/workflows/draft-pdf.yml
.github/workflows/notebooks.yml

Twice per month, run all notebooks in the background.  Part 1 of my response to #461.  Part 2 will be a template repo that gets built as part of the pysindy docs lives outside of pysindy and has its own CI, as a venue for migration.
These tests will help us fix easy notebook issues in the interim and prioritize moving notebooks off of this repo.
I'm going to merge this now, because the last commit switched the notebook job to `on: schedule`, which only runs on master, and can only be tested by merging.
I also disabled the draft-pdf workflow for non-master branches.  It still applies in PR, however.  LMK if that's not desired.

Add notebook review workflow

---

pysindy/utils/axes.py
test/utils/test_axes.py

fix(axes): Handle np.ravel and using poorly-initialized arrays

---

pysindy/optimizers/base.py
pysindy/optimizers/constrained_sr3.py
pysindy/optimizers/sr3.py
pysindy/optimizers/stable_linear_sr3.py
pysindy/optimizers/stlsq.py
pysindy/optimizers/trapping_sr3.py
test/test_optimizers.py
test/test_optimizers_complexity.py

This PR simplifies TrappingSR3, reducing it by about 250 lines.  It changes the base class to `ConstrainedSR3`, deferring all calls to cvxpy to that superclass.  It also makes the main algorithm clearer, so that its easier to see how different initialization arguments affect the choice of math involved (mostly because I couldn't quite understand this from the docstring).  As a related effect, the `_reduce` method more closely matches the algorithm in the paper.
The plan is to eventually utilize superclass for combining and applying constraints, since that class is capable of doing both equality and inequality constraints, which will make it easier to include the constraints and helper functions of example 8 into trapping_sr3.py

Make TrappingSR3 a subclass of ConstrainedSR3

---

pyproject.toml

CVXPY has historically used ECOS, but recently switched to a new solver clarabel.  This causes certain failures due to different arguments (max_iter vs max_iters)

BLD: Limit CVXPY version

---

.github/workflows/main.yml
pysindy/feature_library/polynomial_library.py
pysindy/optimizers/trapping_sr3.py
test/test_optimizers.py

Similar to #499, this implements a test for PL and PQ as well as improves those functions and CI.
Implements the fix in 483f8f4.

Trapping resolve

---

.github/workflows/main.yml
examples/8_trapping_sindy_examples/requirements.txt
pysindy/optimizers/trapping_sr3.py
test/optimizers/test_optimizers.py

This PR extracts the simplified routines for creating the projection tensors.  The simplification is possible because of explicitly relying on the `PolynomialLibrary` through the helper function `_build_lib_info`, which allows methods to look up indexes for relevant terms.  As a result, the PQ and PL matrices now have tests to ensure they are built correctly.
We also remove the `check_P_tensors` function, because we have explicit tests.
Finally, this also
* moves a few other helper functions from master into trapping_extended to further limit the merge conflicts.
* cherry-picks a commit from master to improve CI
For review, start with the tests, then the projection calculations.  If desired, see the helper functions.

Align projection tensor calculations with master

---

pyproject.toml

Arviz uses scipy.signal.gaussian, which was removed in 1.13.  Most recent arviz uses scipy.signal.windows.gaussian
scikit-learn 1.5.0 contained a regression
(https://github.com/scikit-learn/scikit-learn/pull/28352) that has been fixed in
https://github.com/scikit-learn/scikit-learn/pull/29078

BLD: Fix broken versions

---

examples/8_trapping_sindy_examples/trapping_sindy_paper_examples.py
examples/8_trapping_sindy_examples/trapping_utils.py
pysindy/optimizers/trapping_sr3.py
test/test_optimizers.py

Draft - still need to properly handle relax_optim

Begin incorporating notebook from trapping_extended and aligning `__init__`

---

.gitattributes
.github/workflows/main.yml
pysindy/feature_library/polynomial_library.py
pysindy/optimizers/base.py
pysindy/optimizers/constrained_sr3.py
pysindy/optimizers/sr3.py
pysindy/optimizers/trapping_sr3.py
test/conftest.py

This consists of backporting all changes that conflict with master.  trapping-resolve consists of the complement of those changes, i.e. resolution of conflicts on the master branch

Trapping extended jake

---

pyproject.toml
pysindy/__init__.py
pysindy/optimizers/sr3.py

Fix #414, remove user warning suppression from pysindy.
The side effect of this PR is the number of warnings in the test files will increase from 139 to 533.
Most warnings are from `StableLinearSR3` and `TrappingSR3` optimizers throwing warnings if given default parameters.

BUG: #414 remove user warning suppression

---

pysindy/feature_library/pde_library.py
pysindy/feature_library/weak_pde_library.py

CLN(pde_library): remove unused constructor argument

---

pysindy/pysindy.py
test/test_pysindy.py

#448 add flush options to model.print

ENH: #448 print flush

---

.readthedocs.yml

Some recent bugfixes require `derivative>=0.6.2`, which is marked as 3.9+
So RTFD needs at least 3.9.  I gave it an extra couple years

DOC: bump RTD version to allow compatible packages

---

.gitattributes

Since notebooks now shadow existing code, they (over)duplicate line change statistics.

CLN: Ignore notebooks in GH language stats

---

.gitattributes

Since notebooks now copy existing code, there's no point in counting them in the language stats at all.

CLN: Ignore notebooks in code count

---

.github/workflows/main.yml
pysindy/_typing.py
pysindy/optimizers/base.py
pysindy/optimizers/sbr.py
test/test_optimizers/test_optimizers.py

This PR implements some changes to testing:
1) Tests involving SBR use a much smaller `num_warmup`, `num_samples` than the default arguments.
2) nuts_kwargs added to allow fine control of the sampler (to allow faster termination in tests)
3) column normalization is extracted from BaseOptimizer.fit so that it can be tested independently.  The test no longer is parametrized across all subclasses, but rather just tests the helper function.
4) Do a few more notebook tests in CI.

Speed up SBR tests, and add NUTS kwargs

---

pyproject.toml
pysindy/_typing.py
pysindy/feature_library/__init__.py
pysindy/feature_library/base.py
pysindy/feature_library/polynomial_library.py
pysindy/optimizers/base.py
pysindy/optimizers/trapping_sr3.py
pysindy/pysindy.py
pysindy/utils/__init__.py
pysindy/utils/_axis_conventions.py
pysindy/utils/base.py
test/conftest.py

Begin #351
This pull request begins the abstraction of the `SINDy` class, which handles a lot of methods with special cases, to a variety of classes that reflect fundamental differences between problem formulations.  Here, I pull out `_BaseSINDy`, which contains basic information about the feature library, system dimension, and printing the equations.
Future PRs will make Weak and discrete their own classes, modify feature libraries to be amenable to jax, numpy, and cvxpy arrays, and introduce the Single-Step SINDy class and associated optimizer/problem setup.

Extract common functionality from `SINDy` to `_BaseSINDy`

---

.github/workflows/draft-pdf.yml
pyproject.toml

Future work will be needed to update dependency info for, e.g. compatibility with scikit-learn and cvxpy

BLD: Limit numpy to <2.0

---

.github/workflows/release.yml

[Action](https://github.com/Jacob-Stevens-Haas/mitosis/actions/runs/14026712826/job/39266594107) has failure:
```
Checking dist/pysindy-2.0.0rc2-py3-none-any.whl: ERROR    InvalidDistribution: Metadata is missing required fields: Name,        
Version.                                                               
Make sure the distribution includes the files where those fields are   
specified, and is using a supported Metadata-Version: 1.0, 1.1, 1.2,   
2.0, 2.1, 2.2.                                                         
```
This is due to an out-of-date twine dependency in the old version of the github action.
This commit bumps the version of the pypi publish action

CI: Bump version of publish action

---

pysindy/optimizers/base.py

This PR updates the default value of `n_subset` in `EnsembleOptimizer` to respect the bootstrap sampling convention when `replace=True`.
This change aligns the implementation with both the docstring and classical bootstrap theory (Efron, 1979), as discussed in [Issue #617](https://github.com/dynamicslab/pysindy/issues/617).

Fix default n_subset based on replace flag (bootstrap logic)

---

.github/workflows/master-to-main.yml

This will allow people to use "main" as references for event triggers and environments.
Eventually, `main` will become default branch.

BLD: Begin shadowing 'master' with 'main'
